"""Map observed ATT&CK techniques to MITRE threat groups.

Reads the compact local lookup generated by scripts/build_group_map.py (which
extracts group -> technique "uses" relationships from the official MITRE ATT&CK
STIX bundle). Runtime is offline and dependency-free — no network, no API key.

This is the grounding boundary for threat-actor context: group names come from
MITRE, never from the LLM, so attribution context can't be hallucinated.
"""
import json
import re
from functools import lru_cache
from pathlib import Path

from .models import GroupMatch

_MAP_PATH = (
    Path(__file__).resolve().parents[1] / "data" / "mitre" / "technique_groups.json"
)
_TCODE_RE = re.compile(r"T\d{4}(?:\.\d{3})?")


@lru_cache(maxsize=1)
def load_group_map() -> dict:
    """Load and cache the technique -> groups lookup."""
    with _MAP_PATH.open() as f:
        return json.load(f)


def _tcode(text: str) -> str | None:
    """Extract a T-code from a technique string like 'T1566.002 - Phishing…'."""
    match = _TCODE_RE.search(text)
    return match.group(0) if match else None


def _parent(tcode: str) -> str | None:
    """Parent technique of a sub-technique, e.g. T1566.002 -> T1566."""
    return tcode.split(".")[0] if "." in tcode else None


def match_groups(techniques: list[str], top_n: int = 5) -> list[GroupMatch]:
    """Return threat groups whose TTPs overlap the given techniques.

    A sub-technique also matches groups documented for its parent (a
    sub-technique is a specific case of the parent), but not vice versa.
    Groups are ranked by how many of the observed techniques they use;
    ties break alphabetically for deterministic output.
    """
    data = load_group_map()
    tech_map: dict[str, list[str]] = data["techniques"]
    groups_meta: dict[str, dict] = data["groups"]

    # Canonical, de-duplicated input T-codes (preserve first-seen order)
    input_codes: list[str] = []
    seen: set[str] = set()
    for entry in techniques:
        code = _tcode(entry)
        if code and code not in seen:
            seen.add(code)
            input_codes.append(code)

    # group name -> set of input codes it is documented to use
    hits: dict[str, set[str]] = {}
    for code in input_codes:
        lookup_codes = [code]
        parent = _parent(code)
        if parent:
            lookup_codes.append(parent)
        matched: set[str] = set()
        for lc in lookup_codes:
            matched.update(tech_map.get(lc, []))
        for group in matched:
            hits.setdefault(group, set()).add(code)

    ranked = sorted(hits.items(), key=lambda kv: (-len(kv[1]), kv[0]))[:top_n]

    return [
        GroupMatch(
            group=name,
            aliases=groups_meta.get(name, {}).get("aliases", [])[:4],
            matched_techniques=sorted(codes),
            overlap_count=len(codes),
        )
        for name, codes in ranked
    ]
